language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
install:
  - go get -u github.com/kardianos/govendor
script:
  - sh coverage.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
